
/************************************/
/** FeedOS C++ Client API          **/
/**                                **/
/** copyright QuantHouse 2003-2008 **/
/**                                **/
/************************************/

FEEDOS_DEF_FIX_SECTYPE (ABS		, "Asset-backed Securities")
FEEDOS_DEF_FIX_SECTYPE (AMENDED	, "Amended &amp; Restated")
FEEDOS_DEF_FIX_SECTYPE (AN		, "Other Anticipation Notes (BAN, GAN, etc.)")
FEEDOS_DEF_FIX_SECTYPE (BA		, "Bankers Acceptance")
FEEDOS_DEF_FIX_SECTYPE (BN		, "Bank Notes")
FEEDOS_DEF_FIX_SECTYPE (BOX		, "Bill Of Exchanges")
FEEDOS_DEF_FIX_SECTYPE (BRADY	, "Brady Bond")
FEEDOS_DEF_FIX_SECTYPE (BRIDGE	, "Bridge Loan")
FEEDOS_DEF_FIX_SECTYPE (BUYSELL	, "Buy Sellback")
FEEDOS_DEF_FIX_SECTYPE (CB		, "Convertible Bond")
FEEDOS_DEF_FIX_SECTYPE (CD		, "Certificate Of Deposit")
FEEDOS_DEF_FIX_SECTYPE (CL		, "Call Loans")
FEEDOS_DEF_FIX_SECTYPE (CMBS	, "Corp. Mortgage-backed Securities")
FEEDOS_DEF_FIX_SECTYPE (CMO		, "Collateralized Mortgage Obligation")
FEEDOS_DEF_FIX_SECTYPE (COFO	, "Certificate Of Obligation")
FEEDOS_DEF_FIX_SECTYPE (COFP	, "Certificate Of Participation")
FEEDOS_DEF_FIX_SECTYPE (CORP	, "Corporate Bond")
FEEDOS_DEF_FIX_SECTYPE (CP		, "Commercial Paper")
FEEDOS_DEF_FIX_SECTYPE (CPP		, "Corporate Private Placement")
FEEDOS_DEF_FIX_SECTYPE (CS		, "Common Stock")
FEEDOS_DEF_FIX_SECTYPE (DEFLTED	, "Defaulted")
FEEDOS_DEF_FIX_SECTYPE (DINP	, "Debtor In Possession")
FEEDOS_DEF_FIX_SECTYPE (DN		, "Deposit Notes")
FEEDOS_DEF_FIX_SECTYPE (DUAL	, "Dual Currency")
FEEDOS_DEF_FIX_SECTYPE (EUCD	, "Euro Certificate Of Deposit")
FEEDOS_DEF_FIX_SECTYPE (EUCORP	, "Euro Corporate Bond")
FEEDOS_DEF_FIX_SECTYPE (EUCP	, "Euro Commercial Paper")
FEEDOS_DEF_FIX_SECTYPE (EUSOV	, "Euro Sovereigns *")
FEEDOS_DEF_FIX_SECTYPE (EUSUPRA	, "Euro Supranational Coupons *")
FEEDOS_DEF_FIX_SECTYPE (FAC		, "Federal Agency Coupon")
FEEDOS_DEF_FIX_SECTYPE (FADN	, "Federal Agency Discount Note")
FEEDOS_DEF_FIX_SECTYPE (FOR		, "Foreign Exchange Contract")
FEEDOS_DEF_FIX_SECTYPE (FORWARD	, "Forward")
FEEDOS_DEF_FIX_SECTYPE (FUT		, "Future")
FEEDOS_DEF_FIX_SECTYPE (GO		, "General Obligation Bonds")
FEEDOS_DEF_FIX_SECTYPE (IET		, "IOETTE Mortgage")
FEEDOS_DEF_FIX_SECTYPE (LOFC	, "Letter Of Credit")
FEEDOS_DEF_FIX_SECTYPE (LQN		, "Liquidity Note")
FEEDOS_DEF_FIX_SECTYPE (MATURED	, "Matured")
FEEDOS_DEF_FIX_SECTYPE (MBS		, "Mortgage-backed Securities")
FEEDOS_DEF_FIX_SECTYPE (MF		, "Mutual Fund")
FEEDOS_DEF_FIX_SECTYPE (MIO		, "Mortgage Interest Only")
FEEDOS_DEF_FIX_SECTYPE (MLEG	, "Multileg Instrument")
FEEDOS_DEF_FIX_SECTYPE (MPO		, "Mortgage Principal Only")
FEEDOS_DEF_FIX_SECTYPE (MPP		, "Mortgage Private Placement")
FEEDOS_DEF_FIX_SECTYPE (MPT		, "Miscellaneous Pass-through")
FEEDOS_DEF_FIX_SECTYPE (MT		, "Mandatory Tender")
FEEDOS_DEF_FIX_SECTYPE (MTN		, "Medium Term Notes")
FEEDOS_DEF_FIX_SECTYPE (NONE	, "No Security Type")
FEEDOS_DEF_FIX_SECTYPE (ONITE	, "Overnight")
FEEDOS_DEF_FIX_SECTYPE (OPT		, "Option")
FEEDOS_DEF_FIX_SECTYPE (PEF		, "Private Export Funding *")
FEEDOS_DEF_FIX_SECTYPE (PFAND	, "Pfandbriefe *")
FEEDOS_DEF_FIX_SECTYPE (PN		, "Promissory Note")
FEEDOS_DEF_FIX_SECTYPE (PS		, "Preferred Stock")
FEEDOS_DEF_FIX_SECTYPE (PZFJ	, "Plazos Fijos")
FEEDOS_DEF_FIX_SECTYPE (RAN		, "Revenue Anticipation Note")
FEEDOS_DEF_FIX_SECTYPE (REPLACD	, "Replaced")
FEEDOS_DEF_FIX_SECTYPE (REPO	, "Repurchase")
FEEDOS_DEF_FIX_SECTYPE (RETIRED	, "Retired")
FEEDOS_DEF_FIX_SECTYPE (REV		, "Revenue Bonds")
FEEDOS_DEF_FIX_SECTYPE (RVLV	, "Revolver Loan")
FEEDOS_DEF_FIX_SECTYPE (RVLVTRM	, "Revolver/Term Loan")
FEEDOS_DEF_FIX_SECTYPE (SECLOAN	, "Securities Loan")
FEEDOS_DEF_FIX_SECTYPE (SECPLEDGE	, "Securities Pledge")
FEEDOS_DEF_FIX_SECTYPE (SPCLA	, "Special Assessment")
FEEDOS_DEF_FIX_SECTYPE (SPCLO	, "Special Obligation")
FEEDOS_DEF_FIX_SECTYPE (SPCLT	, "Special Tax")
FEEDOS_DEF_FIX_SECTYPE (STN		, "Short Term Loan Note")
FEEDOS_DEF_FIX_SECTYPE (STRUCT	, "Structured Notes")
FEEDOS_DEF_FIX_SECTYPE (SUPRA	, "USD Supranational Coupons *")
FEEDOS_DEF_FIX_SECTYPE (SWING	, "Swing Line Facility")
FEEDOS_DEF_FIX_SECTYPE (TAN		, "Tax Anticipation Note")
FEEDOS_DEF_FIX_SECTYPE (TAXA	, "Tax Allocation")
FEEDOS_DEF_FIX_SECTYPE (TBA		, "To Be Announced")
FEEDOS_DEF_FIX_SECTYPE (TBILL	, "US Treasury Bill")
FEEDOS_DEF_FIX_SECTYPE (TBOND	, "US Treasury Bond")
FEEDOS_DEF_FIX_SECTYPE (TCAL	, "Principal Strip Of A Callable Bond Or Note")
FEEDOS_DEF_FIX_SECTYPE (TD		, "Time Deposit")
FEEDOS_DEF_FIX_SECTYPE (TECP	, "Tax Exempt Commercial Paper")
FEEDOS_DEF_FIX_SECTYPE (TERM	, "Term Loan")
FEEDOS_DEF_FIX_SECTYPE (TINT	, "Interest Strip From Any Bond Or Note")
FEEDOS_DEF_FIX_SECTYPE (TIPS	, "Treasury Inflation Protected Securities")
FEEDOS_DEF_FIX_SECTYPE (TNOTE	, "US Treasury Note")
FEEDOS_DEF_FIX_SECTYPE (TPRN	, "Principal Strip From A Non-Callable Bond Or Note")
FEEDOS_DEF_FIX_SECTYPE (TRAN	, "Tax Revenue Anticipation Note")
FEEDOS_DEF_FIX_SECTYPE (UST		, "US Treasury Note (Deprecated Value Use TNOTE)")
FEEDOS_DEF_FIX_SECTYPE (USTB	, "US Treasury Bill (Deprecated Value Use TBILL)")
FEEDOS_DEF_FIX_SECTYPE (VRDN	, "Variable Rate Demand Note")
FEEDOS_DEF_FIX_SECTYPE (WAR		, "Warrant")
FEEDOS_DEF_FIX_SECTYPE (WITHDRN	, "Withdrawn")
//FEEDOS_DEF_FIX_SECTYPE (WLD		, "Wildcard Entry (was "?" in 4.4, used on Security Definition Request message)")
FEEDOS_DEF_FIX_SECTYPE (XCN		, "Extended Comm Note")
FEEDOS_DEF_FIX_SECTYPE (XLINKD	, "Indexed Linked")
FEEDOS_DEF_FIX_SECTYPE (YANK	, "Yankee Corporate Bond")
FEEDOS_DEF_FIX_SECTYPE (YCD		, "Yankee Certificate Of Deposit")
FEEDOS_DEF_FIX_SECTYPE (OOP		, "Options on Physical")
FEEDOS_DEF_FIX_SECTYPE (OOF		, "Options on Futures")
FEEDOS_DEF_FIX_SECTYPE (CASH	, "Cash")

#undef FEEDOS_DEF_FIX_SECTYPE
