
// from FIX protocol 5.0 sp1
// values sent in Context/TAG_TradeCondition


// see http://fixprotocol.org/FIXimate3.0/?sel_language=en&sel_version=FIX.5.0SP1


FEEDOS_DECLARE_FIX_TRADE_CONDITION (cash_only_market						, A, "Cash (only) Market"							)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (average_price_trade						, B, "Average Price Trade"							)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (cash_trade_same_day_clearing			, C, "Cash Trade (same day clearing)"				)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (next_day_only_market					, D, "Next Day (only)Market"						)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (opening_reopening_trade_detail			, E, "Opening/Reopening Trade Detail"				)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (intraday_trade_detail					, F, "Intraday Trade Detail"						)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (rule_127_trade_nyse						, G, "Rule 127 Trade (NYSE)"						)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (rule_155_trade_amex						, H, "Rule 155 Trade (AMEX)"						)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (sold_last_late_reporting				, I, "Sold Last (late reporting)"					)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (next_day_trade_next_day_clearing		, J, "Next Day Trade (next day clearing)"			)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (opened_late_report_of_opened_trade		, K, "Opened (late report of opened trade)"			)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (seller									, L, "Seller"										)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (sold_out_of_sequence					, M, "Sold (out of sequence)"						)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (stopped_stock							, N, "Stopped Stock (guarantee of price but does not execute the order)"	)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (imbalance_more_buyers					, P, "Imbalance More Buyers"						)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (imbalance_more_sellers					, Q, "Imbalance More Sellers"						)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (opening_price							, R, "Opening Price"								)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (bargain_condition_lse					, S, "Bargain Condition (LSE)"						)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (converted_price_indicator				, T, "Converted Price Indicator"					)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (exchange_last							, U, "Exchange Last"								)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (final_price_of_session					, V, "Final Price of Session"						)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (ex_pit									, W, "Ex-pit"										)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (crossed									, X, "Crossed"										)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (trade_resulting_from_manual_slow_quote	, Y, "Trade resulting from manual/slow quote"		)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (trade_resulting_from_intermarket_sweep	, Z, "Trade resulting from intermarket sweep"		)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (volume_only								, a, "Volume Only"				)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (direct_plus								, b, "Direct Plus"				)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (acquisition								, c, "Acquisition"				)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (bunched									, d, "Bunched"					)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (distribution							, e, "Distribution"				)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (bunched_sale							, f, "Bunched Sale"				)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (split_trade								, g, "Split Trade"				)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (cancel_stopped							, h, "Cancel Stopped"			)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (cancel_eth								, i, "Cancel ETH"				)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (cancel_stopped_eth						, j, "Cancel Stopped ETH"		)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (out_of_sequence_eth						, k, "Out of Sequence ETH"		)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (cancel_last_eth							, l, "Cancel Last ETH"			)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (sold_last_sale_eth						, m, "Sold Last Sale ETH"		)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (cancel_last								, n, "Cancel Last"				)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (sold_last_sale							, o, "Sold Last Sale"			)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (cancel_open								, p, "Cancel Open"				)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (cancel_open_eth							, q, "Cancel Open ETH"			)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (opened_sale_eth							, r, "Opened Sale ETH"			)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (cancel_only								, s, "Cancel Only"				)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (cancel_only_eth							, t, "Cancel Only ETH"			)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (late_open_eth							, u, "Late Open ETH"			)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (auto_execution_eth						, v, "Auto Execution ETH"		)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (reopen									, w, "Reopen"					)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (reopen_eth								, x, "Reopen ETH"				)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (adjusted								, y, "Adjusted"					)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (adjusted_eth							, z, "Adjusted ETH"				)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (spread									, AA, "Spread"					)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (spread_eth								, AB, "Spread ETH"				)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (straddle								, AC, "Straddle"				)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (straddle_eth							, AD, "Straddle ETH"			)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (stopped									, AE, "Stopped"					)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (stopped_eth								, AF, "Stopped ETH"				)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (regular_eth								, AG, "Regular ETH"				)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (combo									, AH, "Combo"					)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (combo_eth								, AI, "Combo ETH"				)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (official_closing_price					, AJ, "Official Closing Price"	)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (prior_reference_price					, AK, "Prior Reference Price"	)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (cancel									, 0,  "Cancel"					)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (stopped_sold_last						, AL, "Stopped Sold Last"		)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (stopped_out_of_sequence					, AM, "Stopped Out of Sequence"	)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (offical_closing_price					, AN, "Offical Closing Price"	)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (crossed									, AO, "Crossed"					)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (fast_market								, AP, "Fast Market"				)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (automatic_execution						, AQ, "Automatic Execution"		)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (form_t									, AR, "Form T"					)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (basket_index							, AS, "Basket Index"			)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (burst_basket							, AT, "Burst Basket"			)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (outside_spread							, AV, "Outside Spread"			)
FEEDOS_DECLARE_FIX_TRADE_CONDITION (implied_trade							,  1, "Implied Trade"			)

#undef FEEDOS_DECLARE_FIX_TRADE_CONDITION
