
// LIFFE DMA
// values sent in Context/MARKET_LIFFE_TradeTypeIndicator

FEEDOS_DECLARE_LIFFE_TRADE_TYPE_INDICATOR(Undefined					,"0")	
FEEDOS_DECLARE_LIFFE_TRADE_TYPE_INDICATOR(Block						,"1")
FEEDOS_DECLARE_LIFFE_TRADE_TYPE_INDICATOR(Basis						,"2")
FEEDOS_DECLARE_LIFFE_TRADE_TYPE_INDICATOR(AgainstActual				,"3")
FEEDOS_DECLARE_LIFFE_TRADE_TYPE_INDICATOR(ExternalMatch				,"4")
FEEDOS_DECLARE_LIFFE_TRADE_TYPE_INDICATOR(ExchangeForSwap			,"5")
FEEDOS_DECLARE_LIFFE_TRADE_TYPE_INDICATOR(ExchangeForPhysical		,"6")
FEEDOS_DECLARE_LIFFE_TRADE_TYPE_INDICATOR(Conventional				,"7")	// implicit default value (it will not be sent)
FEEDOS_DECLARE_LIFFE_TRADE_TYPE_INDICATOR(GuaranteedCross			,"8")
FEEDOS_DECLARE_LIFFE_TRADE_TYPE_INDICATOR(Professional				,"9")
FEEDOS_DECLARE_LIFFE_TRADE_TYPE_INDICATOR(AssetAllocation			,"10")

#undef FEEDOS_DECLARE_LIFFE_TRADE_TYPE_INDICATOR
