
// LSE DMA
// values sent in Context/TAG_MARKET_LSE_TradeTypeIndicator

//
// LSE Market
//

// latest trade types: http://www.londonstockexchange.com/traders-and-brokers/products-services/trading-services/tradelect-parameters.xls
FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (AutomaticTrade,			"AT")	// implicit default value (it will not be sent)
FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (UncrossingTrade,			"UT")
FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (ContraTrade,				"CT")
FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (PreviousDayContra,			"PC")
FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (OrdinaryTrade,				"O")
FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (OrdinaryTradeDelayed,		"OK")
FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (NegotiatedTrade,			"NT")
FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (NegotiatedTradeDelayed,	"NK")
FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (LateTradeCorrection,		"LC")
FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (NotToMark,					"NM")
FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (OTCTrade,					"OT")
FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (OTCTradeDelayed,			"TK")
FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (InterFundCrossDelayed,		"IF")
FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (LateOTCTradeCorrection,	"OC")
FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (SITrade,					"SI")
FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (SITradeDelayed,			"SK")
FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (LateSITradeCorrection,		"SC")



//
// JSE Market
//
FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (AssetSwap,											"AS")
//FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (AutomaticTrade,									"AT")	already defined for LSE
FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (JSEBlockTrade,										"BT")
FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (CorporateFinanceTrade,								"CF")
//FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (ContraTrade,										"CT")	already defined for LSE
FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (LateTradeAfterHours,								"LT")
FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (NamibiaTrade,										"NX")
FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (OptionDelta,										"OD")
FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (OffOrderBookPrincipal,								"OP")
FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (OptionExercised,									"OX")
//FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (PreviousDayContra,								"PC")	already defined for LSE
FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (PortfolioTrade,									"PF")
FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (SettlementSpecifiedTrade,							"SS")
FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (TestSecurity,										"TS")
FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (TradeOptionExercised,								"TX")
//FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (UncrossingTrade,									"UT")	already defined for LSE
FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR (WarrantExercised,									"WX")

#undef FEEDOS_DECLARE_LSE_TRADE_TYPE_INDICATOR

/*

// values sent in Context/TAG_MARKET_LSE_BargainConditions
// any combination of the following:

FEEDOS_DECLARE_LSE_BARGAIN_CONDITIONS (SpecialCumBonus					,"CB")
FEEDOS_DECLARE_LSE_BARGAIN_CONDITIONS (SpecialCumCoupon					,"CC")
FEEDOS_DECLARE_LSE_BARGAIN_CONDITIONS (SpecialCumDividend				,"CD")
FEEDOS_DECLARE_LSE_BARGAIN_CONDITIONS (SpecialCumCapitalRepayments		,"CP")
FEEDOS_DECLARE_LSE_BARGAIN_CONDITIONS (SpecialCumRights					,"CR")
FEEDOS_DECLARE_LSE_BARGAIN_CONDITIONS (CashSettlement					,"CS")
FEEDOS_DECLARE_LSE_BARGAIN_CONDITIONS (GuaranteedDelivery				,"GD")
FEEDOS_DECLARE_LSE_BARGAIN_CONDITIONS (SpecialPrice						,"SP")
FEEDOS_DECLARE_LSE_BARGAIN_CONDITIONS (ReportInAccordanceWithChapter8	,"TR")
FEEDOS_DECLARE_LSE_BARGAIN_CONDITIONS (SpecialExBonus					,"XB")
FEEDOS_DECLARE_LSE_BARGAIN_CONDITIONS (SpecialExCoupon					,"XC")
FEEDOS_DECLARE_LSE_BARGAIN_CONDITIONS (SpecialExDividend				,"XD")
FEEDOS_DECLARE_LSE_BARGAIN_CONDITIONS (SpecialExCapitalRepayments		,"XP")
FEEDOS_DECLARE_LSE_BARGAIN_CONDITIONS (SpecialExRights					,"XR")
 
#undef FEEDOS_DECLARE_LSE_BARGAIN_CONDITION

*/

FEEDOS_DECLARE_LSE_BARGAIN_CONDITION_INDICATOR(Yes,"Y")
FEEDOS_DECLARE_LSE_BARGAIN_CONDITION_INDICATOR(No,"N")					// implicit default value (it will not be sent)
FEEDOS_DECLARE_LSE_BARGAIN_CONDITION_INDICATOR(UnknownForContraTrade," ")

#undef FEEDOS_DECLARE_LSE_BARGAIN_CONDITION_INDICATOR

FEEDOS_DECLARE_LSE_CONVERTED_PRICE_INDICATOR(Yes,"Y")
FEEDOS_DECLARE_LSE_CONVERTED_PRICE_INDICATOR(No,"N")					// implicit default value (it will not be sent)
FEEDOS_DECLARE_LSE_CONVERTED_PRICE_INDICATOR(UnknownForContraTrade," ")

#undef FEEDOS_DECLARE_LSE_CONVERTED_PRICE_INDICATOR

FEEDOS_DECLARE_LSE_TRADE_TIME_INDICATOR(Normal,"N")						// implicit default value (it will not be sent)
FEEDOS_DECLARE_LSE_TRADE_TIME_INDICATOR(Late,"L")
FEEDOS_DECLARE_LSE_TRADE_TIME_INDICATOR(Overnight,"O")

#undef FEEDOS_DECLARE_LSE_TRADE_TIME_INDICATOR
